"""create schedule event

Revision ID: 7c657a14600a
Revises: 56b46dbbe5dc
Create Date: 2023-05-12 20:38:03.822071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c657a14600a'
down_revision = '56b46dbbe5dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_schedule',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('event_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("UPDATE event SET fee = 0")
    op.alter_column('event', 'fee',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53), server_default="0",
               nullable=False)
    op.drop_column('event', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.alter_column('event', 'fee',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_table('event_schedule')
    # ### end Alembic commands ###
