"""fix subs

Revision ID: 8da0de2dc127
Revises: 91c6b5e16e77
Create Date: 2023-05-16 15:11:37.797626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8da0de2dc127'
down_revision = '91c6b5e16e77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('schedule_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_constraint('subscription_event_id_fkey', 'subscription', type_='foreignkey')
    op.create_foreign_key(None, 'subscription', 'event_schedule', ['schedule_id'], ['id'], ondelete='CASCADE')
    op.drop_column('subscription', 'event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('event_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.create_foreign_key('subscription_event_id_fkey', 'subscription', 'event', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_column('subscription', 'schedule_id')
    # ### end Alembic commands ###
