"""phone-change

Revision ID: c3ada914373a
Revises: 97dc04fa5532
Create Date: 2023-05-06 21:36:18.436373

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ada914373a'
down_revision = '97dc04fa5532'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True))
    op.drop_column('user', 'country_code')
    op.drop_column('user', '_phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('country_code', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
