"""add canceling

Revision ID: cde3db3df31d
Revises: e9d819b52910
Create Date: 2023-05-16 19:27:15.565776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde3db3df31d'
down_revision = 'e9d819b52910'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('event_schedule', sa.Column('is_canceled', sa.Boolean()))
    op.execute("UPDATE event_schedule SET is_canceled = False")
    op.alter_column('event_schedule', 'is_canceled', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_schedule', 'is_canceled')
    # ### end Alembic commands ###
