"""fix subs2

Revision ID: e9d819b52910
Revises: 8da0de2dc127
Create Date: 2023-05-16 15:42:11.022077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d819b52910'
down_revision = '8da0de2dc127'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_foreign_con_user_schedule', 'subscription', ['schedule_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_foreign_con_user_schedule', 'subscription', type_='unique')
    # ### end Alembic commands ###
